programmer_notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('programmer_notebooks.urls', 'programmer_notebooks'), namespace='programmer_notebooks'))
]

programmer_notebooks/urls.py
"""Defines URL patterns for programmer_notebooks"""

from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    # Home Page
    path('', index, name='index'),

    # Topics Page (all topics)
    path('topics', topics, name='topics'),

    # Topic Page (individual topic)
    path('topics/<int:topic_id>', topic, name='topic')
]

programmer_notebooks/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    # A topic the user wants to take notes about
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    # A spefic note related to the topic
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        # Return a string representaion of the model
        return self.text[:50] + "..."

programmer_notebooks/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
    return render(request, 'programmer_notebooks/index.html')


def topics(request):
    # Show all topics
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'programmer_notebooks/topics.html', context)


def topic(request, topic_id):
    # Show a single topic and all of its entries
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'programmer_notebooks/topic.html', context)

programmer_notebooks/templates/programmer_notebooks/base.html
<p>
    <a href="{% url 'programmer_notebooks:index' %}">Programmer Notebook</a> - 
    <a href="{% url 'programmer_notebooks:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

programmer_notebooks/templates/programmer_notebooks/index.html
{% extends "programmer_notebooks/base.html" %}

{% block content %}
    <p>Programmer Notebook helps you keep track of your learning, for any programming topic you're learning about.</p>
{% endblock content %}

programmer_notebooks/templates/programmer_notebooks/topic.html
{% extends 'programmer_notebooks/base.html' %}

{% block content %}

    <p>Topic: {{ topic }}</p>

    <p>Entries:</p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
    </ul>

{% endblock content %}

programmer_notebooks/templates/programmer_notebooks/topics.html
{% extends "programmer_notebooks/base.html" %}

{% block content %}

    <p>Topic</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'programmer_notebooks:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}